name: CI / Reports Generation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code ï¸
        uses: actions/checkout@v4

      - name: Build and Run Docker Containers ğŸ³
        run: make ci-build

      - name: Install Composer Dependencies
        run: make ci-install

      - name: Run PHPUnit and Generate Coverage HTML
        run: |
          mkdir -p build/coverage
          make ci-coverage-report

      - name: Run Infection and Generate HTML Report
        run: make ci-mutation-report

      - name: Deploy Reports to gh-pages branch ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build
          destination_dir: reports
